name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Install .NET MAUI workload
      run: |
        dotnet workload install maui
        dotnet workload install maui-android
        dotnet workload install maui-ios
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./transcribe.io/
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./transcribe.io/
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./transcribe.io/
